version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    build: ./postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d

volumes:
  postgres: